// Design Tokens - Flutter Dart
// Generated by Token Exporter
// https://github.com/n8mills-UI/token-exporter-showcase

import 'package:flutter/material.dart';

class DesignTokens {
  // Private constructor to prevent instantiation
  DesignTokens._();
  
  // Brand Colors
  static const Color colorBrandPrimary = Color(0xFFD2FF37);
  static const Color colorBrandSecondary = Color(0xFFFF37D2);
  
  // Neutral Colors
  static const Color colorNeutral900 = Color(0xFF171717);
  
  // Font Sizes
  static const double fontSizeBase = 16.0;
  static const double fontSizeLg = 20.0;
  
  // Font Weights
  static const FontWeight fontWeightRegular = FontWeight.w400;
  static const FontWeight fontWeightBold = FontWeight.w700;
  
  // Spacing
  static const double spacingSm = 8.0;
  static const double spacingMd = 16.0;
  static const double spacingLg = 24.0;
  
  // Border Radius
  static const double radiusMd = 6.0;
  
  // Helper method for responsive spacing
  static EdgeInsets paddingSymmetric({
    double horizontal = 0,
    double vertical = 0,
  }) {
    return EdgeInsets.symmetric(
      horizontal: horizontal,
      vertical: vertical,
    );
  }
}