// Design Tokens - Swift
// Generated by Token Exporter
// https://figma.com/@nate/token-exporter

import SwiftUI

struct DesignTokens {
    // MARK: - Brand Colors
    static let brandPrimary = Color(hex: "#D2FF37")
    static let brandSecondary = Color(hex: "#FF37D2")
    static let brandAccent = Color(hex: "#37FFD2")
    
    // MARK: - Neutral Colors
    static let gray50 = Color(hex: "#FAFAFA")
    static let gray100 = Color(hex: "#F5F5F5")
    static let gray200 = Color(hex: "#E5E5E5")
    static let gray300 = Color(hex: "#D4D4D4")
    static let gray400 = Color(hex: "#A3A3A3")
    static let gray500 = Color(hex: "#737373")
    static let gray600 = Color(hex: "#525252")
    static let gray700 = Color(hex: "#404040")
    static let gray800 = Color(hex: "#262626")
    static let gray900 = Color(hex: "#171717")
    
    // MARK: - Typography
    static let fontSizeXS: CGFloat = 12
    static let fontSizeSM: CGFloat = 14
    static let fontSizeBase: CGFloat = 16
    static let fontSizeLG: CGFloat = 18
    static let fontSizeXL: CGFloat = 20
    static let fontSize2XL: CGFloat = 24
    static let fontSize3XL: CGFloat = 30
    static let fontSize4XL: CGFloat = 36
    
    // MARK: - Spacing
    static let spacingXS: CGFloat = 4
    static let spacingSM: CGFloat = 8
    static let spacingMD: CGFloat = 16
    static let spacingLG: CGFloat = 24
    static let spacingXL: CGFloat = 32
    static let spacing2XL: CGFloat = 48
    static let spacing3XL: CGFloat = 64
    
    // MARK: - Border Radius
    static let radiusSM: CGFloat = 2
    static let radiusMD: CGFloat = 6
    static let radiusLG: CGFloat = 8
    static let radiusXL: CGFloat = 12
    static let radius2XL: CGFloat = 16
    static let radiusFull: CGFloat = 9999
}