[build]
  command = "npm run build:optimized"
  publish = "docs"
  
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefix=/opt/buildhome/.npm-global"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Performance headers
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "text/css; charset=utf-8"

# Redirects for clean URLs
[[redirects]]
  from = "/plugin"
  to = "/plugin.html"
  status = 200

# Deploy preview configuration
[context.deploy-preview]
  command = "npm run build:optimized"
  
[context.branch-deploy]
  command = "npm run build:optimized"

# Environment-specific builds
[context.production]
  command = "npm run ci:deploy"

# Plugin for Figma
[[plugins]]
  package = "netlify-plugin-checklinks"
  
  [plugins.inputs]
    entryPoints = [
      "docs/design-system-guide.html"
    ]
    recursive = true
    pretty = true
    
# Build performance optimizations
[build.processing]
  skip_processing = false
  
[build.processing.css]
  bundle = false
  minify = true
  
[build.processing.js]
  bundle = false
  minify = true
  
[build.processing.html]
  pretty_urls = true